export const REQUEST_CATEGORY_TREE = 'REQUEST_CATEGORY_TREE';
export const RECEIVE_CATEGORY_TREE = 'RECEIVE_CATEGORY_TREE';
export const HTTP_ERROR = 'HTTP_ERROR';
export const UPDATE_CATEGORY_TREE = 'UPDATE_CATEGORY_TREE';

